### PR TITLE
Fix/incorrect slot custom targeting

### PR DESCRIPTION
**Pull request by ray1028**

### CODE REVIEW

**Comment by tomattone** [comment]
thanks my friend! 🤘🏻

**Comment by ray1028** [comment]
@tomattone , i notice the code is missing https://www.npmjs.com/package/react-ad-manager/v/1.1.3?activeTab=code

**Comment by tomattone** [comment]
@ray1028 sorry, my bad! its okay now! https://www.npmjs.com/package/react-ad-manager

**Comment by ray1028** [comment]
awesome 🔥  !

**Pull request merged**
